config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  resources :campgrounds, except: [:new, :edit] do
    resources :comments, only: [:new, :create]
  end
  
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  
  get 'new/campground', to: 'campgrounds#new'
  
  get 'edit/campground/:id', to: 'campgrounds#edit', as: 'edit_campground'
  
  get 'users/:id', to: 'users#show', as: 'user'
  
  root 'welcome#index'
  
end

app/models/campground.rb
class Campground < ActiveRecord::Base
	
	def to_param
		"#{id} #{name}".parameterize
	end
	
	belongs_to :user
	
	has_many :comments, dependent: :destroy
	
	validates :user, presence: true
	
	validates :name, presence: true, length: {minimum: 3, maximum: 30},
		uniqueness: {case_sensitive: false}

	validates :url, presence: true, length: {minimum: 10, maximum: 150}

	validates :description, presence: true, length: {minimum: 10, maximum: 800}

	validate :url_valid
	
	protected
	
		def url_valid
			if self.url.downcase.include?(" ")
				errors.add(:url, "Invalid url.")
			end
		end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :campground
	belongs_to :user
	validates :campground, presence: true
	validates :user, presence: true
	validates :data, presence: true, length: {minimum: 3, maximum: 30}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campgrounds
  
  has_many :comments
  
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates_format_of :email, :with => VALID_EMAIL_REGEX
  validates :email, presence: true, length: {minimum: 6, maximum: 25},
    uniqueness: { case_sensitive: false }

  VALID_USERNAME_REGEX = /\A[a-z0-9\-_]+\z/i
  validates_format_of :username, :with => VALID_USERNAME_REGEX
  validates :username, presence: true, length: {minimum: 3, maximum: 25},
    uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/campgrounds_controller.rb
class CampgroundsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destory]
	before_action :find_campground, only: [:show, :edit, :update, :destroy]
	before_action :is_owner, only: [:edit, :update, :destroy]
	def index
		@campgrounds = Campground.all.order('created_at DESC')
	end
	
	def show
		@campground = Campground.find(params[:id])
		@user = @campground.user
		@comments = @campground.comments.order("created_at DESC")
	end
	
	def new
		@campground = Campground.new
	end
	
	def create
		@campground = Campground.new(campground_params)
		@campground.user = current_user
		
		if @campground.save
			flash[:success] = "Saved \"#{@campground.name}\"."
			redirect_to campgrounds_path
		else
			flash[:danger] = "Could not save campground."
			render 'new'
		end
	end

	def edit
	end
	def update
		if @campground.update(campground_params)
			flash[:success] = "Updated \"#{@campground.name}\"."
			redirect_to @campground
		else
			flash[:danger] = "Error updating campground."
			render 'edit'
		end
	end
  
	def destroy
		if @campground.destroy
			flash[:success] = "Deleted the campground."
		else
			flash[:danger] = "Could not delete the campground."
		end
		redirect_to campgrounds_path
	end
  
	private
	
		def find_campground
			@campground = Campground.find(params[:id])
		end

		def campground_params
			params.require(:campground).permit(:name, :url, :description) 
		end

		def is_owner
			if @campground.user != current_user
				flash[:danger] = "You can only do that with your campgrounds."
				redirect_to @campground
			end
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_campground
  before_action :authenticate_user!
  def new
    @comment = Campground.comments.build
  end
  def create
    @comment = @campground.comments.new(comment_params)
    @comment.user = current_user
    if current_user.nil?
      flash[:danger] = "You need to be signed in to do that."
      redirect_to new_user_session_path
    else
      @comment.save
      redirect_to campground_path(@campground)
    end
  end
  
  def index
    @comments = @campground.comments.order("created_at DESC")
  end
  
  private
  
    def comment_params
      params.require(:comment).permit(:data)
    end
    
    def load_campground
      @campground = Campground.find(params[:campground_id])
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campgrounds_helper.rb
module CampgroundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/campgrounds/_form.html.erb
<%= form_for @campground do |f| %>
	<h1><%= @name %></h1>
	<div class="form-group">
		<%= f.label :name, class: 'sr-only' %>
		<%= f.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: true %>
	</div>
	<div class="form-group">
		<%= f.label :url, class: 'sr-only' %>
		<%= f.text_field :url, class: 'form-control', placeholder: 'Image url' %>
	</div>
	<div class="form-group">
		<%= f.label :description, class: 'sr-only' %>
		<%= f.text_area :description, class: 'form-control', placeholder: 'Description', rows: '5' %>
	</div>
	<div class="form-group text-left">
		<%= f.submit name, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/campgrounds/edit.html.erb
<div class="container">
	<% @title = "Editing campground - YelpCamp" %>
	<div class="well well-transparent col-md-6 col-md-offset-3">
        <% @name = 'Edit campground' %>
        <%= render 'form', name: "Edit" %>
    </div>
</div>

app/views/campgrounds/index.html.erb
<div class="container">
	<h1 class="text-center">Listing all campgrounds</h1>
	<div class="row" style="display:flex; flex-wrap: wrap;">
		<% @campgrounds.each do |campground| %>
			<div class="col-md-3 col-sm-6">
				<div class="thumbnail">
					<%= image_tag(campground.url, onerror: 'imgerror(this)') %>
					<div class="caption">
						<%= link_to campground.name, campground_path(campground) %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/campgrounds/new.html.erb
<div class="container">
    <div class="well well-transparent col-md-6 col-md-offset-3">
        <% @name = 'Create a campground' %>
        <%= render 'form', name: 'New campground' %>
    </div>
</div>

app/views/campgrounds/show.html.erb
<div class="container">
	<div class="col-md-8">
		<div class="thumbnail">
			<%= image_tag(@campground.url, onerror: 'imgerror(this)') %>
			<div class="caption">
				<h4><%= @campground.name %> <small><i><%= if current_user != @user then link_to @user.username, user_path(@user) else link_to "you", user_path(@user) end %></i></small></h4>
				<p><%= @campground.description %></p>
				<% if current_user == @campground.user %>
					<%= link_to 'edit', edit_campground_path(@campground), class: 'btn btn-primary btn-xs' %>
					<%= link_to 'delete', campground_path(@campground), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-4" id="comments">
		<% if user_signed_in? %>
			<%= render 'comments/new' %>
		<% else %>
			<strong>Login to comment.</strong>
			<br><br>
		<% end %>
		<div class="comments-all">
			<%= render 'comments/index' %>
		</div>
	</div>
	<br><br><br><br><br><br><br><br><br><br>
</div>

app/views/comments/_index.html.erb
<% @comments.each do |comment| %>
	<p><%= comment.data %> <span class="pull-right"><small><i><%= comment.user.username %></i></small></span></p>
<% end %>

app/views/comments/_new.html.erb
<%= form_for([@campground, @campground.comments.build]) do |f| %>
	<div class="form-group">
		<%= f.label :data, class: 'sr-only' %>
		<%= f.text_field :data, rows: 2, class: 'form-control', placeholder: 'Add a comment', maxlength: 30 %>
	</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
	<div class="alert alert-<%= key %>" role="alert">
		<div class="container text-center">
			<strong><%= msg %></strong>
		</div>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!--<a href="/" class="pull-left"><img src="/img/logo.png" height="70"></a>-->
			<%= link_to 'YelpCamp', root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if !current_page?(controller: '/campgrounds', action: 'new') && user_signed_in? %>
					<li><%= link_to 'New Campground', new_campground_path %></li>
				<% end %>
				<% if !current_page?(controller: '/campgrounds', action: 'index') %>
					<li><%= link_to 'All campgrounds', campgrounds_path %></li>
				<% end %>
				<% if !user_signed_in? && !current_page?(controller: 'devise/sessions', action: 'new') %>
					<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>
				<% if user_signed_in? %>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yelpcamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: "#{controller_name}-#{action_name}" do %>

  <%= render 'layouts/messages' %>

  <%= render 'layouts/nav' %>

  <%= yield %>
  
  <footer>
    <div class="container container-fluid" style="padding: 20px; color: #fff">
      a project by Samarth Dave
    </div>
  </footer>

<% end %>
</html>

app/views/users/show.html.erb
<div class="container">
	<div class="jumbotron">
		<% if current_user == @user %>
			<h1>Your profile</h1>
		<% else %>
			<h1><%= @user.username %>'s profile</h1>
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="container text-center">
	<div class="jumbotron">
		<h1>Welcome to YelpCamp!</h1>
		<p>A place to share your favorite camping trips.</p>
		<%= link_to "Sign up now", new_user_registration_path, class: 'btn btn-success' if !user_signed_in? %>
	</div>
</div>